const roster = [
    {
        name: "D'angelo Russell",
        number: 1,
        id: 1,
        position: "Point Guard",
        image: "images/d'angelorussell.png",
        highlight: "https://www.youtube.com/embed/HEy3Ljfs6pI?autoplay=1&mute=1&loop=1&playlist=HEy3Ljfs6pI&controls=0&showinfo=0&rel=0&modestbranding=1",
        stats : {
            points: 18.0,
            assists: 6.3,
            rebounds: 3.1,
            steals: 0.9,
            blocks: 0.5
        },
        advancedStats: {
            gamesPlayed: 76,
            gamesStarted: 69,
            minutesPerGame: 32.7,
            pointsPerGame: 18.0,
            assistsPerGame: 6.3,
            reboundsPerGame: 2.2,
            offensiveReboundsPerGame: 0.4,
            defensiveReboundsPerGame: 2.7,
            stealsPerGame: 0.9,
            blocksPerGame: 0.5,
            fieldGoalMade: 6.5,
            fieldGoalAttempted: 14.2,
            fieldGoalPercentage: 45.6,
            threePointMade: 3.0,
            threePointAttempted: 7.2,
            threePointPercentage: 41.5,
            freeThrowMade: 2.1,
            freeThrowAttempted: 2.5,
            freeThrowPercentage: 82.8,
            turnoversPerGame: 2.1,
            personalFoulsPerGame: 2.1,
            trueShootingPercentage: 56.7,
            plusMinus: 1.2

        },
        basicStats: {
            height: `6'3"`,
            feet: 6,
            inches: 3,
            weight: 200,
            age: 27,
            birthdate: "Feb 23, 1996",
            country: "USA",
            draftPick: "R1 P2 2015",
            aquired: "Trade 2023",
            experience: "9 Years"
        }
    },
    {
        name: "Jarred Vanderbilt",
        number: 2,
        id: 2,
        position: "Power Forward",
        image: "images/jarredvanderbilt.png",
        highlight: "https://www.youtube.com/embed/SDaAmtjT9eg?autoplay=1&mute=1&loop=1&playlist=SDaAmtjT9eg&controls=0&showinfo=0&rel=0&modestbranding=1",
        stats: {
            points: 5.2,
            assists: 1.2,
            rebounds: 4.8,
            steals: 1.2,
            blocks: 0.2
        },
        advancedStats: {
            gamesPlayed: 29,
            gamesStarted: 6,
            minutesPerGame: 20.0,
            pointsPerGame: 5.2,
            assistsPerGame: 1.2,
            reboundsPerGame: 4.8,
            offensiveReboundsPerGame: 1.4,
            defensiveReboundsPerGame: 3.3,
            stealsPerGame: 1.2,
            blocksPerGame: 0.2,
            fieldGoalMade: 2.0,
            fieldGoalAttempted: 3.9,
            fieldGoalPercentage: 51.8,
            threePointMade: 0.3,
            threePointAttempted: 0.9,
            threePointPercentage: 29.6,
            freeThrowMade: 0.8,
            freeThrowAttempted: 1.2,
            freeThrowPercentage: 66.7,
            turnoversPerGame: 1.0,
            personalFoulsPerGame: 1.5,
            trueShootingPercentage: 40.1,
            plusMinus: -0.3
        },
        basicStats: {
            height: `6'9"`,
            feet: 6,
            inches: 9,
            weight: 230,
            age: 24,
            birthdate: "Apr 3, 1999",
            country: "USA",
            draftPick: "R2 P41 2018",
            aquired: "Trade 2023",
            experience: "5 Years"
        }

    },
    {
        name: "Anthony Davis",
        number: 3,
        id: 3,
        position: "Center",
        image: "images/anthonydavis.png",
        highlight: "https://www.youtube.com/embed/YOJjIQDuNhY?autoplay=1&mute=1&loop=1&playlist=YOJjIQDuNhY&controls=0&showinfo=0&rel=0&modestbranding=1",
        stats: {
            points: 24.7,
            assists: 3.5,
            rebounds: 12.6,
            steals: 1.2,
            blocks: 2.3
        },
        advancedStats: {
            gamesPlayed: 76,
            gamesStarted: 76,
            minutesPerGame: 35.5,
            pointsPerGame: 24.7,
            assistsPerGame: 3.5,
            reboundsPerGame: 12.6,
            offensiveReboundsPerGame: 3.1,
            defensiveReboundsPerGame: 9.5,
            stealsPerGame: 1.2,
            blocksPerGame: 2.3,
            fieldGoalMade: 9.4,
            fieldGoalAttempted: 16.9,
            fieldGoalPercentage: 55.6,
            threePointMade: 0.4,
            threePointAttempted: 1.4,
            threePointPercentage: 27.1,
            freeThrowMade: 5.5,
            freeThrowAttempted: 6.8,
            freeThrowPercentage: 81.6,
            turnoversPerGame: 2.1,
            personalFoulsPerGame: 2.3,
            trueShootingPercentage: 61.2,
            plusMinus: 2.1
        },
        basicStats: {
            height: `6'10"`,
            feet: 6,
            inches: 10,
            weight: 253,
            age: 30,
            birthdate: "Mar 11, 1993",
            country: "USA",
            draftPick: "R1 P1 2012",
            aquired: "Trade 2019",
            experience: "12 Years"
        }
    },
    {
        name: "Cam Reddish",
        number: 5,
        id: 4,
        position: "Small Forward",
        image: "images/camreddish.png",
        highlight: "https://www.youtube.com/embed/2aLrJlGGW1U?autoplay=1&mute=1&loop=1&playlist=2aLrJlGGW1U&controls=0&showinfo=0&rel=0&modestbranding=1",
        stats: {
            points: 5.4,
            assists: 1.0,
            rebounds: 2.1,
            steals: 1.0,
            blocks: 0.3
        },
        advancedStats: {
            gamesPlayed: 48,
            gamesStarted: 26,
            minutesPerGame: 20.5,
            pointsPerGame: 5.4,
            assistsPerGame: 1.0,
            reboundsPerGame: 2.1,
            offensiveReboundsPerGame: 0.6,
            defensiveReboundsPerGame: 1.5,
            stealsPerGame: 1.0,
            blocksPerGame: 0.3,
            fieldGoalMade: 1.9,
            fieldGoalAttempted: 4.9,
            fieldGoalPercentage: 38.9,
            threePointMade: 0.8,
            threePointAttempted: 2.3,
            threePointPercentage: 33.6,
            freeThrowMade: 0.9,
            freeThrowAttempted: 1.1,
            freeThrowPercentage: 75.9,
            turnoversPerGame: 0.6,
            personalFoulsPerGame: 1.3,
            trueShootingPercentage: 50.1,
            plusMinus: -1.2
        },
        basicStats: {
            height: `6'8"`,
            feet: 6,
            inches: 8,
            weight: 218,
            age: 24,
            birthdate: "Sep 1, 1999",
            country: "USA",
            draftPick: "R1 P10 2018",
            aquired: "Trade 2023",
            experience: "6 Years"
        }

    },
    {
        name: "Gabe Vincent",
        number: 7,
        id: 5,
        position: "Point Guard",
        image: "images/gabevincent.png",
        highlight: "https://www.youtube.com/embed/uym_2Cih1Ro?autoplay=1&mute=1&loop=1&playlist=uym_2Cih1Ro&controls=0&showinfo=0&rel=0&modestbranding=1",
        stats: {
            points: 3.1,
            assists: 1.9,
            rebounds: 0.8,
            steals: 0.8,
            blocks: 0.0
        },
        advancedStats: {
            gamesPlayed: 11,
            gamesStarted: 0,
            minutesPerGame: 19.8,
            pointsPerGame: 3.1,
            assistsPerGame: 1.9,
            reboundsPerGame: 0.8,
            offensiveReboundsPerGame: 0.4,
            defensiveReboundsPerGame: 0.5,
            stealsPerGame: 0.8,
            blocksPerGame: 0.0,
            fieldGoalMade: 1.4,
            fieldGoalAttempted: 4.5,
            fieldGoalPercentage: 30.6,
            threePointMade: 0.3,
            threePointAttempted: 2.5,
            threePointPercentage: 10.7,
            freeThrowMade: 0.1,
            freeThrowAttempted: 0.2,
            freeThrowPercentage: 50.0,
            turnoversPerGame: 0.5,
            personalFoulsPerGame: 1.7,
            trueShootingPercentage: 36.2,
            plusMinus: -3.2
        },
        basicStats: {
            height: `6'3"`,
            feet: 6,
            inches: 3,
            weight: 200,
            age: 27,
            birthdate: "Jun 14, 1996",
            country: "USA",
            draftPick: "Undrafted 2018",
            aquired: "Free Agent 2024",
            experience: "6 Years"
        }
    },
    {
        name: "Max Christie",
        number: 12,
        id: 6,
        position: "Shooting Guard",
        image: "images/maxchristie.png",
        highlight: "https://www.youtube.com/embed/ie8XaWvUKEs?autoplay=1&mute=1&loop=1&playlist=ie8XaWvUKEs&controls=0&showinfo=0&rel=0&modestbranding=1",
        stats: {
            points: 4.2,
            assists: 0.9,
            rebounds: 2.1,
            steals: 0.3,
            blocks: 0.3
        },
        advancedStats: {
            gamesPlayed: 67,
            gamesStarted: 7,
            minutesPerGame: 14.1,
            pointsPerGame: 4.2,
            assistsPerGame: 0.9,
            reboundsPerGame: 2.1,
            offensiveReboundsPerGame: 0.2,
            defensiveReboundsPerGame: 1.9,
            stealsPerGame: 0.3,
            blocksPerGame: 0.3,
            fieldGoalMade: 1.5,
            fieldGoalAttempted: 3.6,
            fieldGoalPercentage: 42.7,
            threePointMade: 0.6,
            threePointAttempted: 1.8,
            threePointPercentage: 35.6,
            freeThrowMade: 0.5,
            freeThrowAttempted: 0.7,
            freeThrowPercentage: 78.3,
            turnoversPerGame: 0.5,
            personalFoulsPerGame: 0.9,
            trueShootingPercentage: 38.2,
            plusMinus: -0.5

        },
        basicStats: {
            height: `6'6"`,
            feet: 6,
            inches: 6,
            weight: 210,
            age: 20,
            birthdate: "Feb 10, 2003",
            country: "USA",
            draftPick: "R1 P15 2022",
            aquired: "Draft 2022",
            experience: "2 Years"
        }

    },
    {
        name: "Jaxson Hayes",
        number: 11,
        id: 7,
        position: "Center",
        image: "images/jaxsonhayes.png",
        highlight: "https://www.youtube.com/embed/gGAB_kpMxiE?autoplay=1&mute=1&loop=1&playlist=gGAB_kpMxiE&controls=0&showinfo=0&rel=0&modestbranding=1",
        stats: {
            points: 4.3,
            assists: 0.5,
            rebounds: 3.0,
            steals: 0.5,
            blocks: 0.4
        },
        advancedStats: {
            gamesPlayed: 70,
            gamesStarted: 5,
            minutesPerGame: 12.5,
            pointsPerGame: 4.3,
            assistsPerGame: 0.5,
            reboundsPerGame: 3.0,
            offensiveReboundsPerGame: 1.0,
            defensiveReboundsPerGame: 2.0,
            stealsPerGame: 0.5,
            blocksPerGame: 0.4,
            fieldGoalMade: 1.8,
            fieldGoalAttempted: 2.5,
            fieldGoalPercentage: 72.0,
            threePointMade: 0.0,
            threePointAttempted: 0.1,
            threePointPercentage: 0.0,
            freeThrowMade: 0.7,
            freeThrowAttempted: 1.2,
            freeThrowPercentage: 62.2,
            turnoversPerGame: 0.6,
            personalFoulsPerGame: 1.8,
            trueShootingPercentage: 48.2,
            plusMinus: -0.6
        },
        basicStats: {
            height: `6'11"`,
            feet: 6,
            inches: 11,
            weight: 220,
            age: 21,
            birthdate: "May 23, 2000",
            country: "France",
            draftPick: "R1 P7 2020",
            aquired: "Trade 2023",
            experience: "3 Years"
        }

    },
    {
        name: "Austin Reaves",
        number: 15,
        id: 8,
        position: "Shooting Guard",
        image: "images/austinreaves.png",
        highlight: "https://www.youtube.com/embed/tA9fnxkPiEk?autoplay=1&mute=1&loop=1&playlist=tA9fnxkPiEk&controls=0&showinfo=0&rel=0&modestbranding=1",
        stats: {
            points: 15.9,
            assists: 5.5,
            rebounds: 4.3,
            steals: 0.8,
            blocks: 0.3
        },
        advancedStats: {
            gamesPlayed: 82,
            gamesStarted: 57,
            minutesPerGame: 32.1,
            pointsPerGame: 15.9,
            assistsPerGame: 5.5,
            reboundsPerGame: 4.3,
            offensiveReboundsPerGame: 0.7,
            defensiveReboundsPerGame: 3.6,
            stealsPerGame: 0.8,
            blocksPerGame: 0.3,
            fieldGoalMade: 5.6,
            fieldGoalAttempted: 11.5,
            fieldGoalPercentage: 48.6,
            threePointMade: 1.9,
            threePointAttempted: 5.1,
            threePointPercentage: 36.7,
            freeThrowMade: 2.8,
            freeThrowAttempted: 3.3,
            freeThrowPercentage: 85.3,
            turnoversPerGame: 2.1,
            personalFoulsPerGame: 1.9,
            trueShootingPercentage: 51.2,
            plusMinus: 1.7
        },
        basicStats: {
            height: `6'5"`,
            feet: 6,
            inches: 5,
            weight: 210,
            age: 25,
            birthdate: "Aug 29, 1999",
            country: "USA",
            draftPick: "Undrafted 2021",
            aquired: "Draft 2021",
            experience: "3 Year"
        }
    },
    {
        name: "Maxwell Lewis",
        number: 20,
        id: 9,
        position: "Shooting Guard",
        image: "images/maxwelllewis.png",
        highlight: "https://www.youtube.com/embed/DIW0HRjBCGg?autoplay=1&mute=1&loop=1&playlist=DIW0HRjBCGg&controls=0&showinfo=0&rel=0&modestbranding=1",
        stats: {
            points: 0.3,
            assists: 0.2,
            rebounds: 0.1,
            steals: 0.1,
            blocks: 0.0
        },
        advancedStats: {
            gamesPlayed: 34,
            gamesStarted: 0,
            minutesPerGame: 3.0,
            pointsPerGame: 0.3,
            assistsPerGame: 0.2,
            reboundsPerGame: 0.1,
            offensiveReboundsPerGame: 0.1,
            defensiveReboundsPerGame: 0.1,
            stealsPerGame: 0.1,
            blocksPerGame: 0.0,
            fieldGoalMade: 0.1,
            fieldGoalAttempted: 0.6,
            fieldGoalPercentage: 19.0,
            threePointMade: 0.0,
            threePointAttempted: 0.3,
            threePointPercentage: 11.1,
            freeThrowMade: 0.1,
            freeThrowAttempted: 0.1,
            freeThrowPercentage: 66.7,
            turnoversPerGame: 0.3,
            personalFoulsPerGame: 0.1,
            trueShootingPercentage: 21.0,
            plusMinus: -2.8

        },
        basicStats: {
            height: `6'7"`,
            feet: 6,
            inches: 7,
            weight: 200,
            age: 21,
            birthdate: "Jan 10, 2002",
            country: "USA",
            draftPick: "Undrafted 2023",
            aquired: "Draft 2023",
            experience: "1 Year"
        }
    },
    {
        name: "LeBron James",
        number: 23,
        id: 10,
        position: "Small Forward",
        highlight: "https://www.youtube.com/embed/QiwVq7SGluo?autoplay=1&mute=1&loop=1&playlist=QiwVq7SGluo&controls=0&showinfo=0&rel=0&modestbranding=1",
        image: "images/lebronjames.png",
        stats: {
            points: 25.7,
            assists: 8.3,
            rebounds: 7.3,
            steals: 1.3,
            blocks: 0.5
        },
        advancedStats: {
            gamesPlayed: 71,
            gamesStarted: 71,
            minutesPerGame: 35.3,
            pointsPerGame: 25.7,
            assistsPerGame: 8.3,
            reboundsPerGame: 7.3,
            offensiveReboundsPerGame: 0.9,
            defensiveReboundsPerGame: 6.4,
            stealsPerGame: 1.3,
            blocksPerGame: 0.5,
            fieldGoalMade: 9.6,
            fieldGoalAttempted: 17.9,
            fieldGoalPercentage: 54.0,
            threePointMade: 2.1,
            threePointAttempted: 5.1,
            threePointPercentage: 41.0,
            freeThrowMade: 4.3,
            freeThrowAttempted: 5.7,
            freeThrowPercentage: 75.0,
            turnoversPerGame: 3.5,
            personalFoulsPerGame: 1.1,
            trueShootingPercentage: 55.7,
            plusMinus: 2.0


        },
        basicStats: {
            height: `6'9"`,
            feet: 6,
            inches: 9,
            weight: 250,
            age: 39,
            birthdate: "Dec 30, 1984",
            country: "USA",
            draftPick: "R1 P1 2003",
            aquired: "Free agent 2019",
            experience: "21 Years"
        }
    },
    {
        name: "Rui Hachimura",
        number: 28,
        id: 11,
        position: "Power Forward",
        image: "images/ruihachimura.png",
        highlight: "https://www.youtube.com/embed/5cnA8LQxi0U?autoplay=1&mute=1&loop=1&playlist=5cnA8LQxi0U&controls=0&showinfo=0&rel=0&modestbranding=1",
        stats: {
            points: 13.6,
            assists: 1.2,
            rebounds: 4.3,
            steals: 0.6,
            blocks: 0.4
        },
        advancedStats: {
            gamesPlayed: 68,
            gamesStarted: 39,
            minutesPerGame: 26.9,
            pointsPerGame: 13.6,
            assistsPerGame: 1.2,
            reboundsPerGame: 4.3,
            offensiveReboundsPerGame: 0.9,
            defensiveReboundsPerGame: 3.5,
            stealsPerGame: 0.6,
            blocksPerGame: 0.4,
            fieldGoalMade: 5.3,
            fieldGoalAttempted: 9.9,
            fieldGoalPercentage: 53.7,
            threePointMade: 1.4,
            threePointAttempted: 3.4,
            threePointPercentage: 42.2,
            freeThrowMade: 1.5,
            freeThrowAttempted: 2.0,
            freeThrowPercentage: 73.9,
            turnoversPerGame: 0.7,
            personalFoulsPerGame: 1.5,
            trueShootingPercentage: 49.2,
            plusMinus: 0.9
        },
        basicStats: {
            height: `6'8"`,
            feet: 6,
            inches: 8,
            weight: 230,
            age: 25,
            birthdate: "Feb 8, 1998",
            country: "Japan",
            draftPick: "R1 P9 2019",
            aquired: "Trade 2023",
            experience: "5 Years"
        }
    },
    {
        name: "Christian Wood",
        number: 35,
        id: 12,
        position: "Center",
        image: "images/christianwood.png",
        highlight: "https://www.youtube.com/embed/7Jc-05itGJM?autoplay=1&mute=1&loop=1&playlist=7Jc-05itGJM&controls=0&showinfo=0&rel=0&modestbranding=1",
        stats: {
            points: 6.9,
            assists: 1.0,
            rebounds: 5.1,
            steals: 0.3,
            blocks: 0.7
        },
        advancedStats: {
            gamesPlayed: 50,
            gamesStarted: 1,
            minutesPerGame: 17.4,
            pointsPerGame: 6.9,
            assistsPerGame: 1.0,
            reboundsPerGame: 5.1,
            offensiveReboundsPerGame: 0.8,
            defensiveReboundsPerGame: 4.3,
            stealsPerGame: 0.3,
            blocksPerGame: 0.7,
            fieldGoalMade: 2.5,
            fieldGoalAttempted: 5.3,
            fieldGoalPercentage: 46.6,
            threePointMade: 0.7,
            threePointAttempted: 2.3,
            threePointPercentage: 30.7,
            freeThrowMade: 1.3,
            freeThrowAttempted: 1.9,
            freeThrowPercentage: 70.2,
            turnoversPerGame: 1.0,
            personalFoulsPerGame: 1.4,
            trueShootingPercentage: 53.9,
            plusMinus: 0.1
        },
        basicStats: {
            height: `6'10"`,
            feet: 6,
            inches: 10,
            weight: 214,
            age: 26,
            birthdate: "Sep 27, 1995",
            country: "USA",
            draftPick: "Undrafted 2016",
            aquired: "Trade 2023",
            experience: "7 Years"
        }
    },
]